import time
print("\n\n\n                     Dictionary\n\n")
print("a .-         b -...      c -.-.      d -..       e .         f ..-.\n")
print("g --.        h ....      i ..        j .---      k -.-       l .-..\n")
print("m --         n -.        o ---       p .--.      q --.-      r .-.\n")
print("s ...        t -         u ..-       v ...-      w .--       x-..-\n")
print("y -.--       z --..\n")
print(" |_|  |_|  \____/  |_|  \_\ |_____/  |______|    |_|  \___/   |_|\n\n")
print("A Cole Parks Creation (featuring contributions from Alex Skeldon)\n\n\n\n\n\n\n\n\n\n\n")
time.sleep(5)
print("\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nwhat would you like to do today?\n\n\n")